apiVersion: v2
name: karpenter
description: Karpenter node autoscaling for STACKIT IaaS servers.
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - karpenter
  - autoscaling
  - stackit
home: https://github.com/kubekanvas/karpenter-provider-stackit
sources:
  - https://github.com/kubekanvas/karpenter-provider-stackit
